import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400"],
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable}  antialiased m-0`}
      >
        <div className="h-80 bg-lime-500">
          <div className="max-w-7xl m-auto flex h-full">
            <h1 className="self-end text-white text-6xl">pixelrabbit</h1>
          </div>
        </div>
        <div className="max-w-7xl m-auto">{children}</div>
      </body>
    </html>
  );
}
